In [2]:
#day 2
import numpy as np
A=np.arange(1,13).reshape(3,4)  #reshape(rows,col) 13 not included
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
B=np.linspace(1,3,8).reshape(2,4)
print(B)

[[1.         1.28571429 1.57142857 1.85714286]
 [2.14285714 2.42857143 2.71428571 3.        ]]


In [ ]:
C=np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)  #g,r,c  reshape must store in another variable  resize-dont require another var to store
print(C)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
B=np.array([45,67,89,12,34,51,90,98])
B.resize(2,2,2) #changes the shape of original array
#reshape- changes needs saving in another variable
print(B)

None


In [ ]:
A=np.array([32,12,5,6])   #same no of elements
B=np.array([12,45,89,34])
C=A-B
print(C)

[ 20 -33 -84 -28]


In [ ]:
A=[1,2,34]    #LISTS THROW AN ERROR  list-not iterative
B=[4,5,6]
print(A-B)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
A=np.array([32,12,5,6])   #same no of elements
B=np.array([12,45,89,34])
C=A+B
print(C)

[44 57 94 40]


In [ ]:
A=np.array([32,12,5,6])   #same no of elements
B=np.array([12,45,89,34])
C=A*B
print(C)

[384 540 445 204]


In [ ]:
 import numpy as np
A=np.array([32,12,5,6]).reshape()   #same no of elements
B=np.array([12,45,89,34])
C=A-B
print(C)

TypeError: reshape() takes exactly 1 argument (0 given)

In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)
print(B)
C=A*B
print(C)

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
[[384 540]
 [445 204]]


In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)   #1 to 1 functions
print(B)
C=A@B #matrix multipliaction
print(C)

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
[[1452 1848]
 [ 594  429]]


In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)  #1 to 1 functions
print(B)
C=A.dot(B)    #matrix multipliaction
print(C)

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
[[1452 1848]
 [ 594  429]]


In [ ]:
S=np.array([12,3.2,67,56.7,100,101,2])
print(S.max())
print(A.min())  #max min only accepts numeric datatypes int nad float

101.0
5


In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)
print(B)
print(A.max(axis=0)) #axis=0 =col
print(A.min(axis=1))  #axis=1 =row

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
[32 12]
[12  5]


In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)
print(B)
print("vertical stacking in arrays")  #added on up
print(np.vstack((A,B)))

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
vertical stacking in arrays
[[32 12]
 [ 5  6]
 [12 45]
 [89 34]]


In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)
print(B)
print("horizontal stacking in arrays")  #side by side
print(np.hstack((A,B)))

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
horizontal stacking in arrays
[[32 12 12 45]
 [ 5  6 89 34]]


In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)
print(B)
print("stacking in arrays")
print(np.stack((A,B),axis=0))

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
stacking in arrays
[[[32 12]
  [ 5  6]]

 [[12 45]
  [89 34]]]


In [ ]:
A=np.array([32,12,5,6]).reshape(2,2)   #same no of elements
print(A)
B=np.array([12,45,89,34]).reshape(2,2)
print(B)
print("stacking in arrays")
print(np.stack((A,B),axis=1))

[[32 12]
 [ 5  6]]
[[12 45]
 [89 34]]
stacking in arrays
[[[32 12]
  [12 45]]

 [[ 5  6]
  [89 34]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)   #same no of elements
print(A)
print("after dstacking in arrays")  #no of rows=noof grps
#no: of col in every grp=no: of rows in every grp
#[0,0],[1,1].....
print(np.dstack(A))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
after dstacking in arrays
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)   #same no of elements
print(A)
print("after split")
print(np.vsplit(A,3))  #group

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after split
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)   #same no of elements
print(A)
print("after split")
print(np.vsplit(A,(2,5)))   #as our wish

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after split
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)   #same no of elements
print(A)
print("after split")#hsplit=col vsplit=row
print(np.vsplit(A,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
after split
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(3,6)
print(A)
print("after splitting")
np.hsplit(A,3)  #GROUP

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(3,6)
print(A)
print("after splitting")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
after splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
arr=np.array([12,13,14,15,1,2,3,4,45,23,89,100]).reshape(3,4)
print(arr)
print(arr.argmax())
print(arr.argmax(axis=0))   #returns index
print(arr.argmax(axis=1))


[[ 12  13  14  15]
 [  1   2   3   4]
 [ 45  23  89 100]]
11
[2 2 2 2]
[3 3 3]


In [ ]:
arr=np.array([12,13,14,15,1,22,3,4,45,23,89,100]).reshape(3,4)
print(arr)
print(arr.argmin())
print(arr.argmin(axis=0))
print(arr.argmin(axis=1))

[[ 12  13  14  15]
 [  1  22   3   4]
 [ 45  23  89 100]]
4
[1 0 1 1]
[0 0 1]


# **STATISTICS**

In [ ]:
#mean,median,std,var
A=np.array([12,13,56,78])
print("mean=",np.mean(A))
print("median=",np.median(A))
print("variance=",np.var(A))
print("standard deviation=",np.std(arr))

mean= 39.75
median= 34.5
variance= 803.1875
standard deviation= 31.66085472981142


TRIGONOMETRY

In [ ]:
A=np.pi
print(A)

3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
A=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print(A)

[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
print(np.rad2deg(A))

[ 45.  60.  90. 180.]


In [ ]:
c=np.array([0,30,45,60,90,120,180])
d=np.deg2rad(c)
print(d)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(c)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(c)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(c)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1)  #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1)    #cos^-1

0.0

In [ ]:
np.arctan(1)    #tan^-1

0.7853981633974483

In [ ]:
a=6
b=4
print(np.hypot(a,b))    #hypotneuse

7.211102550927978


Searching in an array

In [ ]:
A=np.array([12,45,1,90,23,54,12,1])
print(np.where(A==12))

(array([0, 6]),)


In [ ]:
A=np.array([12,45,1,90,23,54,12,1])
print(np.where(A%2==0))

(array([0, 3, 5, 6]),)


In [ ]:
A=np.array([12,45,1,90,23,54,12,1])
print(np.where(A>50))

(array([3, 5]),)


In [ ]:
#create an array
#a=np.array([1,2,3,4,5,6,7,8,910,10])    #first sort then search
#outputs the lists from sorted elements
a=np.array([34,12,78,2])
print(np.searchsorted(a,12))
#2 12 34 78

0


linear algebra and ufunc

In [ ]:
A=np.array([10,12,14,16])
B=np.array([1,2,3,4])
print(np.add(A,B))
print(np.subtract(A,B))
print(np.diff(A))
print(np.divide(A,B))#quotient
print(np.divmod(A,B))#quotient and remainder

[11 14 17 20]
[ 9 10 11 12]
[2 2 2]
[10.          6.          4.66666667  4.        ]
(array([10,  6,  4,  4]), array([0, 0, 2, 0]))


In [ ]:
#sort
A=np.array([23,56,12,90,57,91,8,1])
print(np.sort(A))

[ 1  8 12 23 56 57 90 91]


Set functions

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.union1d(a,b))

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=np.array([6,7,8,9,10])
print(np.intersect1d(a,b))

[6]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=np.array([6,7,8,9,10])
print(np.setdiff1d(b,a))

[ 7  8  9 10]


rounding

In [ ]:
#rounding
a=np.trunc([3.1634,4.5621,-123.556])
print(a)



[   3.    4. -123.]


In [ ]:
#rounding
a=np.fix([3.1634,4.5621,-123.567])
print(a)

[   3.    4. -123.]


In [ ]:
#rounding
a=np.around(4.5621,0)
b=np.around(-3.567,0)
print(a)
print(b)

5.0
-4.0


In [ ]:
#rounding
a=np.floor([3.1634,4.6621,-123.567])
print(a)

[   3.    4. -124.]


In [ ]:
#rounding
a=np.ceil([3.1634,4.3621,-123.567])
print(a)

[   4.    5. -123.]


More functions

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.cumsum(a))

[ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.cumprod(a))

[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [ ]:
x=np.lcm(56,38)
print(x)
y=np.gcd(45,89)
print(y)

1064
1


In [ ]:
ar=np.array([12,34,67,89,32,23])
print(np.lcm.reduce(ar))

223827168


In [ ]:
ar=np.array([12,34,67,89,32,23])
print(np.gcd.reduce(ar))

1


In [ ]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a)) #linear algebra inverse

[[-2.   1. ]
 [ 1.5 -0.5]]


from parent import child

In [ ]:
from numpy import random as rd
a=rd.rand()   #default limit 0 to 0.99 or n
print(a)

0.223930891662949


In [ ]:
a=rd.rand(10)   #(no of elements) n numbers
print(a)

[0.88177536 0.70840409 0.84512229 0.77235405 0.6443197  0.40168369
 0.86970273 0.08444365 0.27093314 0.14426438]


In [ ]:
a=rd.randint(5)   #randint(limit) 0,1,2,3,4
print(a)

0


In [ ]:
a=rd.randint(30,size=4)  #limit
print(a)


[23 11 28  0]


In [ ]:
a=rd.randint(30,size=(2,2))  #limit
print(a)


[[11  2]
 [ 6 28]]


joins

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1*4+2*5+3*6
print(np.inner(A,B))

32


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1*(4,5,6) 2*(4,5,6) 3*(4,5,6)
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])#b to a
B=np.array([4,5,6])
print(np.cross(A,B))

[-3  6 -3]
