In [ ]:
#variable
a=10;
print("Iam", a, "years old");


Iam 10 years old


In [ ]:
#arithemetic operators on int vars
a=int(input("enter a value: "));
b=int(input("enter b value: "));
print("sum:a+b=",a+b);
print("diff:a-b=",a-b);
print("pro:a*b=",a*b);
print("qu:a/b=",a/b);
print("mod:a%b=",a%b);
print("expo:a**b=",a**b);
print("floor:a//b=",a//b);


enter a value: 12
enter b value: 2
sum:a+b= 14
diff:a-b= 10
pro:a*b= 24
qu:a/b= 6.0
mod:a%b= 0
expo:a**b= 144
floor:a//b= 6


In [ ]:
#take a number from a user which is a salary if the salary is more than 50000 there is a 10% tax print his final salary
a=int(input("enter salary:"))
if a>=50000:
  print("your salary is:",a-a/10)
else:
  print("no tax")

enter salary:50000
your salary is: 45000.0


In [3]:
#get the salary from user if the salary is more than equal to 50k apply 10 %tax deduction if the salary is less than 50k apply 5% tax if the salary is more than 70k apply 12% tax if your salary exceeds 1l print you are promoted to next level
a=int(input("enter salary:"))
if(a==0):
  print("enter valid salary");
elif(a>0 and a<=50000):
  print("your salary is:",a-a*(5/100))
elif(a>50000 and a<=70000):
  print("your salary is:",a-a*(10/100))
elif(a>70000 and a<=100000):
  print("your salary is:",a-a*(12/100))
else:
  print("you are promoted");




enter salary:75000
your salary is: 66000.0


In [ ]:
#table using for loop
n=int(input("enter a number:"))
for i in range(1,11):
  print(n,"*",i,"=",n*i)


enter a number:13
13 * 1 = 13
13 * 2 = 26
13 * 3 = 39
13 * 4 = 52
13 * 5 = 65
13 * 6 = 78
13 * 7 = 91
13 * 8 = 104
13 * 9 = 117
13 * 10 = 130


In [ ]:
#table using while loop
n=int(input("enter a number:"))
i=1
while(i<11):
  print(n,"*",i,"=",n*i)
  i=i+1


enter a number:5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [4]:
#create a list(heterogeneous)
l=[1,"kill",89,"chat",9.1,True]
for i in l:
  print(i)
print(l)

1
kill
89
chat
9.1
True
[1, 'kill', 89, 'chat', 9.1, True]


In [5]:
#mutable
l=[1,"kill",89,"chat",9.1,True]
print(l)
l.append('added')   #listname.append(element)
print("after append")
print(l)

[1, 'kill', 89, 'chat', 9.1, True]
after append
[1, 'kill', 89, 'chat', 9.1, True, 'added']


In [ ]:
#insert into the list
l.insert(4,'inserted')  #listname.insert(index,element)
print(l)

[1, 'kill', 'inserted', 9.1, 'inserted', 'inserted', True, 'added']


In [ ]:
#pop
l.pop(2)    #listname.pop(index) or#listname.pop() pops last element
print(l)

[1, 'kill', 'chat', 'inserted', 9.1, True, 'added']


In [ ]:
#remove
l.remove("chat")    #listname.remove("element")
print(l)


[1, 'kill', 'inserted', 9.1, True, 'added']


In [ ]:
#adding two lists
l1=[1,2]
l2=[3,4]
#print(l1.extend(l2))  #l1=l1+l2
#print(l1+l2)
l3=l1+l2
print(l3)


[1, 2, 3, 4]


In [ ]:
#clearing the list
l1.clear()
print(l1)

[]


In [ ]:
#create a list of random 10 integer elements print their sqrs save these squares in a new list
l=[1,2,3,4,5,11,12,13,14,15]
l2=[]
for i in l:
  l2.append(i*i)
print(l2)

[1, 4, 9, 16, 25, 121, 144, 169, 196, 225]


In [ ]:
#list comprehension
#newlist=[output for if]
l1=[2,12,34,16]
res=[i*i for i in l1 if i>20]
print(res)

[1156]


In [ ]:
#newlist=[(st of if) if (con) else (st of else) for ]
lis=[23,67,12,34,69]
res=[i*i if i>50 else 'X' for i in lis]
print(res)

['X', 4489, 'X', 'X', 4761]


In [ ]:
#take the salry from the user if the salary is <50k 10% tax oterwise 15% tax
n=int(input("enter salary"))
l4=[]
l4.append(n)
res=[n-(n*10/100)if n<=50000 else n-(n*15/100) ]
print(res)

enter salary100000
[85000.0]


In [ ]:
#taking salary as list
sal_list=[20000,65000,100000,45000]
res=[i-(i*10/100)if i<=50000 else i-(i*15/100)  for i in sal_list]
print(res)

[18000.0, 55250.0, 85000.0, 40500.0]


In [ ]:
#create dictionary
d1={ "mentor":'jwalitha' ,'mentor':'anu',22:'jyo'}  #overwritten
print(d1)
print(d1.keys())
print(d1.values())
print(d1[22])


{'mentor': 'anu', 22: 'jyo'}
dict_keys(['mentor', 22])
dict_values(['anu', 'jyo'])
jyo


In [ ]:
#nested dictionery
d3={"dept":"CSE","details":{"year":"II","sec":"D","count":71}}
print(d3['dept'])
print(d3['details']['sec'])
print("year is:",d3['details']['year'])
print("section is:",d3['details']['sec'])
print("count is:",d3['details']['count'])

CSE
D
year is: II
section is: D
count is: 71


In [ ]:
#making a dictionary from two lists
list1=[1,2,3,4]
list2=["anu","veena","jyo","pallavi"]
new_dic=(zip(list1,list2))
for i in new_dic:
  print(i)


(1, 'anu')
(2, 'veena')
(3, 'jyo')
(4, 'pallavi')


In [ ]:
#making a dictionary from two lists
list1=[1,2,3,4]
list2=["anu","veena","jyo","pallavi"]
new_dic=dict(zip(list1,list2))    #new_dic=dict(zip(list2,list1)) reverse
print(new_dic)

{'anu': 1, 'veena': 2, 'jyo': 3, 'pallavi': 4}


In [ ]:
#numpy
import numpy as np
A=np.array([1,2,3,4])   #1d array
print(A.ndim)     #dimension
print(A.shape)    #only 4 elements
print(A)

1
(4,)
[1 2 3 4]


In [ ]:
B=np.array([[1,2,3,4],[5,6,7,8]])   #2d array
print(B.ndim)   #elements in each row=columns
print(B.shape)    #col=4 row=2
print(B)

2
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
C=np.array([[[12,32,45,122],[43,12,78,123],[2,53,41,124]]])#3d  (g,r,c)
print(C.ndim)
print(C.shape)
print(C)

3
(1, 3, 4)
[[[ 12  32  45 122]
  [ 43  12  78 123]
  [  2  53  41 124]]]


In [ ]:
A=np.ones((2,5,3))    #(g,r,c)
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
A=np.zeros((2,5,3))    #(g,r,c)
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#identity matrix
A=np.eye(4) #rows=cols=4
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:

A=np.arange(1,10,2)
print(A)
print(type(A))    #1D ARRAY

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#PRINT ALL THE NUMS THAT ARE DIVISIBLE BY USING ARANGE FUNCTION B/W 1AND 1000
A=np.arange(8,1001,8)   #(START,UPTO,STEP)
print(A)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
A=np.linspace(48,59,10) #(upper limit,lower limit,division of parts)
print(A)

[48.         49.22222222 50.44444444 51.66666667 52.88888889 54.11111111
 55.33333333 56.55555556 57.77777778 59.        ]


work on tuples and sets and documentations qr

line space
splitting the range of numbers into n numbers with common differences